name: plant_calendar
description: Kleine Kalender App um die GieÃŸzeiten von Zimmerpflanzen zu vermerken

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  flutter_calendar_carousel: 1.3.10

  flutter_colorpicker: 0.2.1

  path_provider: 0.5.0

  sqflite: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.0"

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
